name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, kali]

    steps:
    - uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y python3 python3-pip
        pip3 install --upgrade pip

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        
    - name: Install security tools
      run: |
        apt-get install -y sqlmap
        apt-get install -y nmap
        apt-get install -y wireshark
        apt-get install -y wpscan

    - name: Run tests
      run: |
        pytest --cov=.
        
    - name: Run security tests
      run: |
        # Test SQL injection detection
        python3 scripts/sqlmap_auto.py -u "http://localhost/dvwa/vulnerabilities/sqli/?id=1&Submit=Submit" \
          -c "PHPSESSID=test; security=low" \
          --list-dbs \
          --debug \
          --threads 10 \
          --technique B \
          --dbms MySQL

    - name: Check formatting
      run: |
        black . --check

    - name: Run linter
      run: |
        flake8 .
